admin_panel/urls.py
from admin_panel.models import Tour
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .views import (AdminHomePageView, CreateTourView, TourDetailView, TourDeleteView, TourUpdateView, ajax_delete_images)

urlpatterns = [
    path(
        "login/",
        LoginView.as_view(template_name="admin_panel/login.html"),
        name="login",
    ),
    path(
        "logout/",
        LogoutView.as_view(),
        name="logout",
    ),
    path("home/", AdminHomePageView.as_view(), name="admin_home_view"),
    path("tour/create/", CreateTourView.as_view(), name="create_tour_view"),
    path("tour/<int:pk>", TourDetailView.as_view(), name="tour_detail_view"),
    path("tour/<int:pk>/delete", TourDeleteView.as_view(), name="tour_delete_view"),
    path("tour/<int:pk>/update", TourUpdateView.as_view(), name="tour_update_view"),
    
    path("ajax/delete-images", ajax_delete_images, name="ajax_delete_images")
]

home/urls.py
from django.urls import path
from .views import (
    HomePageView,
)

urlpatterns = [path("", HomePageView.as_view(), name="home_page_view"), ]

travel_website_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('site-admin/', include('admin_panel.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin_panel/models.py
from django.db import models
from django.urls import reverse


class Tour(models.Model):
    
    tour_types = (
        
        ("family", "Family"),
        ("solo", "Solo"),
        ("friends", "Friends"),
        ("adventure", "Adventure"),
        ("nature", "Nature"),
        ("religious", "Religious"),
        ("wildlife", "WildLife"),
    )
    
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=100)
    category = models.CharField(max_length=25, choices=tour_types)
    date = models.DateField()
    price = models.IntegerField()
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('tour_detail_view', args=[str(self.id)])
    
class TourImage(models.Model):
    tour = models.ForeignKey(Tour, default=None, on_delete=models.CASCADE, related_name='tourimage')
    image = models.FileField(upload_to='images/')
    
    def __str__(self):
        return self.tour.name
        

home/models.py
from django.db import models

# Create your models here.

admin_panel/views.py
from django.shortcuts import render, HttpResponse
from django.views.generic import (
    TemplateView,
    CreateView,
    ListView,
    DeleteView,
    UpdateView,
)
from .mixins import TourImageMixin
from django.views import View
from django.urls import reverse_lazy
from django.views.generic.detail import DetailView
from .models import Tour, TourImage
from django.http import JsonResponse


class AdminHomePageView(ListView):
    model = Tour
    context_object_name = "tours"
    paginate_by = 4
    template_name = "admin_panel/view_tours.html"
    
    def get_queryset(self):
        query = self.request.GET.get('query', None)
        queryset = Tour.objects.all()
        
        if query:
            queryset = queryset.filter(name__icontains=query)
        
        return queryset


class CreateTourView(TourImageMixin, CreateView):
    template_name = "admin_panel/create_tour.html"
    

class TourUpdateView(TourImageMixin, UpdateView):
    template_name = "admin_panel/update_tour.html"
    


class TourDetailView(DetailView):
    model = Tour
    template_name = "admin_panel/tour_detail.html"


class TourDeleteView(DeleteView):
    model = Tour
    success_url = reverse_lazy("admin_home_view")


def ajax_delete_images(request):

    image_list = request.POST.getlist("image_list[]")

    for image_id in image_list:
        TourImage.objects.get(id=int(image_id)).delete()

    return JsonResponse({"success": "Images Deleted Successfully"})

home/views.py
from django.shortcuts import render
from django.views.generic import TemplateView


class HomePageView(TemplateView):
    template_name = "index.html"
    context_object_name = "hello"

    # Pass extra data to the template
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        print("!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
        print(context)
        print("!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
        # Pass single variables
        context["temporary"] = "Hello World"
        context["hola"] = "World Hello"

        # Pass dictionary
        context["dict"] = [
            {"me": "My gee", "be": "My bee"},
            {"me": "Baby", "be": "Boba"},
        ]
        return context

admin_panel/templates/admin_panel/admin_home.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />

        <title>Collapsible sidebar using Bootstrap 4</title>

        <!-- Bootstrap CSS CDN -->
        <link
            rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"
            integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4"
            crossorigin="anonymous"
        />
        <!-- Our Custom CSS -->
        <link rel="stylesheet" href="{% static 'css/admin_style.css' %}" />

        <!-- Font Awesome JS -->
        <script
            defer
            src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js"
            integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ"
            crossorigin="anonymous"
        ></script>
        <script
            defer
            src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js"
            integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY"
            crossorigin="anonymous"
        ></script>
    </head>

    <body>
        <div class="wrapper">
            <!-- Sidebar  -->
            <nav id="sidebar">
                <div class="sidebar-header">
                    <h3>Bootstrap Sidebar</h3>
                </div>

                <ul class="list-unstyled components">
                    <p>Dummy Heading</p>
                    <li class="active">
                        <a href="{% url 'admin_home_view' %}">Home</a>
                    </li>
                    <li>
                        <a href="{% url 'create_tour_view' %}">Create Tour</a>
                    </li>
                    <li>
                        <a
                            href="#pageSubmenu"
                            data-toggle="collapse"
                            aria-expanded="false"
                            class="dropdown-toggle"
                            >Pages</a
                        >
                        <ul class="collapse list-unstyled" id="pageSubmenu">
                            <li>
                                <a href="#">Page 1</a>
                            </li>
                            <li>
                                <a href="#">Page 2</a>
                            </li>
                            <li>
                                <a href="#">Page 3</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="#">Portfolio</a>
                    </li>
                    <li>
                        <a href="#">Contact</a>
                    </li>
                </ul>
            </nav>

            <!-- Page Content  -->
            <div id="content">
                <nav class="navbar navbar-expand-lg navbar-light bg-light">
                    <div class="container-fluid">
                        <button
                            type="button"
                            id="sidebarCollapse"
                            class="btn btn-info"
                        >
                            <i class="fas fa-align-left"></i>
                            <span>Hello, {{ user.username }}</span>
                        </button>
                        <button
                            class="btn btn-dark d-inline-block d-lg-none ml-auto"
                            type="button"
                            data-toggle="collapse"
                            data-target="#navbarSupportedContent"
                            aria-controls="navbarSupportedContent"
                            aria-expanded="false"
                            aria-label="Toggle navigation"
                        >
                            <i class="fas fa-align-justify"></i>
                        </button>

                        <div
                            class="collapse navbar-collapse"
                            id="navbarSupportedContent"
                        >
                            <ul class="nav navbar-nav ml-auto">
                                <!-- <li class="nav-item active">
                                    <a class="nav-link" href="#">Page</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="#">Page</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="#">Page</a>
                                </li> -->
                                <li class="nav-item">
                                    <div class="navigation">
                                        <a
                                            href="{% url 'logout' %}"
                                            class="btn btn-info btn-lg"
                                        >
                                            <span
                                                class="glyphicon glyphicon-log-out"
                                            ></span>
                                            Logout
                                        </a>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                </nav>

                {% block content %} {% endblock content %}
            </div>
        </div>

        <script
        src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous">
        </script>
        <script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
        <!-- Popper.JS -->
        <script
            src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"
            integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ"
            crossorigin="anonymous"
        ></script>
        <!-- Bootstrap JS -->
        <script
            src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"
            integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm"
            crossorigin="anonymous"
        ></script>

        <script type="text/javascript" src="{% static 'js/app.js' %}""></script>
        {% block scripts %} {% endblock scripts %}
    </body>
</html>

admin_panel/templates/admin_panel/create_tour.html
{% extends "admin_panel/admin_home.html" %} {% block content %}<!--/////-->
{% load crispy_forms_tags %}
<center>
    <h1>Create Tour Page</h1>
    <div class="card-deck shadow-lg p-3 mb-5 bg-faded rounded">
        <div class="card-body">
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %} {{ form | crispy }}
                <div class="form-group">
                    <label for="id_price" class="requiredField">
                        Upload Images<span class="asteriskField">*</span>
                    </label>
                    <div>
                        <input
                            class="form-control"
                            type="file"
                            id="files"
                            name="extra_images"
                            multiple
                        />
                    </div>
                </div>
                <br />
                <input type="submit" value="Save" />
            </form>
        </div>
    </div>
    <!-- <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %} {{ form | crispy }}
        <input
            type="file"
            id="files"
            name="extra_images"
            multiple
        /><br /><br />
        <input type="submit" value="Save" />
    </form> -->
    {% endblock content %}
</center>

admin_panel/templates/admin_panel/login.html
<!------ Include the above in your HEAD tag ---------->
{% load static %} {% load crispy_forms_tags %}
<!DOCTYPE html>
<html>
    <head>
        <title>Login Page</title>
        <!--Made with love by Mutiullah Samim -->

        <!--Bootsrap 4 CDN-->
        <link
            rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
            integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
            crossorigin="anonymous"
        />

        <!--Fontawesome CDN-->
        <link
            rel="stylesheet"
            href="https://use.fontawesome.com/releases/v5.3.1/css/all.css"
            integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU"
            crossorigin="anonymous"
        />

        <!--Custom styles-->
        <link
            rel="stylesheet"
            type="text/css"
            href="{% static 'css/style.css' %}"
        />
    </head>
    <body>
        <div class="container">
            <div class="d-flex justify-content-center h-100">
                <div class="card">
                    <div class="card-header">
                        <h3>Sign In</h3>
                        <div class="d-flex justify-content-end social_icon">
                            <span><i class="fab fa-facebook-square"></i></span>
                            <span
                                ><i class="fab fa-google-plus-square"></i
                            ></span>
                            <span><i class="fab fa-twitter-square"></i></span>
                        </div>
                    </div>
                    <form method="post">
                        {% csrf_token %} {{ form | crispy }}
                        <button type="submit">Log In</button>
                    </form>
                </div>
            </div>
        </div>
    </body>
</html>

admin_panel/templates/admin_panel/tour_detail.html
{% extends "admin_panel/admin_home.html" %} {% block content %}
<div class="post-entry">
    <h2>Detail page</h2>
    <h2>{{ tour.name }}</h2>
    <p>{{ tour.description }}</p>
    <p>{{ tour.category }}</p>
    <p>{{ tour.date }}</p>
    <p>{{ tour.price }}</p>
    <div class="row">
        {% for image in tour.tourimage.all %}
        <div class="col-md-4" style="padding-bottom: 10px">
            <div class="thumbnail">
                <img
                    src="{{ image.image.url }}"
                    alt="Lights"
                    width="300"
                    height="250"
                    style="border: None"
                />
            </div>
        </div>
        {% endfor %}
    </div>
</div>
<p>
    <a class="btn btn-warning" href="{% url 'tour_update_view' tour.pk %}">Edit Tour </a>
    <span>&nbsp;&nbsp;&nbsp;&nbsp;</span>
    <form method="POST" action="{% url 'tour_delete_view' tour.pk %}">
        {% csrf_token %} <input class="btn btn-danger" type="submit" value="Delete Tour">
    </form>
</p>
{% endblock content %}

admin_panel/templates/admin_panel/update_tour.html
{% extends "admin_panel/admin_home.html" %} {% block content %}<!---->
{% load crispy_forms_tags %}
<div class="container">
    <h1>Edit post</h1>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %} {{ form | crispy }}
        <div class="row">
            {% for image in tour.tourimage.all %}
            <div class="col-md-4" style="padding-bottom: 10px">
                {{image.id}}
                <div class="thumbnail">
                    <img
                        src="{{ image.image.url }}"
                        alt="Lights"
                        width="300"
                        height="250"
                        data-image-id="{{image.id}}"
                    />
                </div>
            </div>
            {% endfor %}
        </div>
        <br />
        <button id="delete-images" class="btn btn-danger" type="button">
            Delete Selected Images
        </button>
        <br /><br />
        <div class="form-group">
            <label for="id_price" class="requiredField">
                Add New Images<span class="asteriskField">*</span>
            </label>
            <div>
                <input
                    class="form-control"
                    type="file"
                    id="files"
                    name="extra_images"
                    multiple
                />
            </div>
        </div>
        <br /><br />
        <input type="submit" value="Save Changes" />
    </form>
</div>
{% endblock content %}
<!---->
{% load static %}
<!---->
{% block scripts %}
<script src="{% static 'js/create_tour.js' %}"></script>
<script type="text/javascript">
    window.CSRF_TOKEN = "{{ csrf_token }}";
</script>
{% endblock scripts %}

admin_panel/templates/admin_panel/view_tours.html
{% extends "admin_panel/admin_home.html" %} {% block content %}<!---->
{% load filters %}
<div class="container">
    <div class="card-deck shadow-lg p-3 mb-5 bg-faded rounded">
        <div class="card bg-danger">
            <div class="card-body">
                <center>
                    <h5 class="card-title">Unresolved Inquiries</h5>
                    <h1 class="card-text">25</h1>
                </center>
            </div>
        </div>
        <div class="card bg-primary">
            <div class="card-body">
                <center>
                    <h5 class="card-title">Tours Remaining</h5>
                    <h1 class="card-text">25</h1>
                </center>
            </div>
        </div>
        <div class="card bg-success">
            <div class="card-body">
                <center>
                    <h5 class="card-title">Tours Completed</h5>
                    <h1 class="card-text">25</h1>
                </center>
            </div>
        </div>
    </div>

    <!-- Working on this -->
    <form action="{% url 'admin_home_view' %}" method="GET">
        <input type="text" placeholder="Search" name="query" />
        <input type="submit" value="Search" />
    </form>
    <div class="card-deck row">
        {% for tour in tours %}
        <div class="col-xs-12 col-sm-6 col-md-4">
            <div class="card">
                <div class="view overlay">
                    <a href="{% url 'tour_detail_view' tour.pk %}">
                        <img
                            class="card-img-top"
                            src="{{tour | tour_image_url}}"
                            alt="Card image cap"
                            width="250"
                            height="200"
                        />
                    </a>
                    <a href="#!">
                        <div class="mask rgba-white-slight"></div>
                    </a>
                </div>

                <div class="card-body">
                    <h4 class="card-title">
                        <a href="{% url 'tour_detail_view' tour.pk %}"
                            >{{tour.name}}
                        </a>
                    </h4>
                    <p class="card-text">{{tour.description}}</p>
                    <p class="card-text"><b style="color: black;">{{tour.price}} &#8377;</b></p></b>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>

    <br /><br />
    <div class="pagination">
        <span class="step-links">
            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages}}.
            </span>
            <br /><br />
            {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %} {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
</div>
{% endblock content %}